# -*- coding: utf-8 -*-
"""Vaga de Estágio Análise e Desenvolvimento - Ribeirão Preto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j1xQ9rZCoo5tVariPkKT15He4kDO_-2U
"""

import math

#Questão 1
print()
print('Questão 1')
INDICE = 13 
SOMA = 0 
K = 0;
while K < INDICE:
  K = K + 1;
SOMA = SOMA + K;
print("Resultado Final : " + str(SOMA));
print()
#Resultado Ao Final é 13

#Questão 2
def isPerfectSquare(x):
    s = int(math.sqrt(x))
    return s*s == x
def isFibonacci(n):
    return isPerfectSquare(5*n*n + 4) or isPerfectSquare(5*n*n - 4)

valor = 1
if (valor == True):
    print(valor,"pertence a sequencia de Fibonacci")
else:
    print(valor,"não pertence a sequencia de Fibonacci")
print()
#Questão 3
#
# a) 1, 3, 5, 7, ___                  ->  9, numeros impares
# b) 2, 4, 8, 16, 32, 64, ____        ->  128, o dobro do anterior
# c) 0, 1, 4, 9, 16, 25, 36, ____     ->  49, numeros quadrados
# d) 4, 16, 36, 64, ____              ->  100
# e) 1, 1, 2, 3, 5, 8, ____           ->  13, Sequência de Fibonacci
# f) 2,10, 12, 16, 17, 18, 19, ____   ->  200, numeros que começa com a letra D
#
#Questão 4
#
#
#
#
#Questão 5
print('Questão 5')
string = 'Você pode olhar todas as minhas fotos e mesmo assim sair daqui sem me conhecer'
string_reversa = string[::-1]
print(string_reversa)
print()